version: "3.8"
services:
  rabbit:
    image: rabbitmq

  fastapi:
    image: celery_second_step
    ports:
      - 8080:8080
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 8080

  worker:
    image: celery_second_step
    entrypoint: celery -A proj worker -l INFO
