[tool.poetry]
name = "second-step"
version = "0.1.0"
description = ""
authors = ["hoang <giahoangth@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
celery = "^5.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
